### PR TITLE
Fix undefined method in 16.2.44

### PR DESCRIPTION
**Pull request by rnt**
In chef 16.2.44 this recipe raise a compile error:

```
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/sshd-test/recipes/default.rb
       ================================================================================
       
       NoMethodError
       -------------
       undefined method `openssh_server' for cookbook: sshd, recipe: default :Chef::Recipe
       
       Cookbook Trace: (most recent call first)
       ----------------------------------------
         /tmp/kitchen/cache/cookbooks/sshd/recipes/default.rb:33:in `from_file'
         /tmp/kitchen/cache/cookbooks/sshd-test/recipes/default.rb:1:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/sshd/recipes/default.rb:
       
        26:  directory File.dirname(node['sshd']['config_file']) do
        27:    owner  'root'
        28:    group  node['root_group']
        29:    mode   0o755
        30:  end
        31:  
        32:  # Configure service
        33>> openssh_server node['sshd']['config_file'] do
        34:    name            node['sshd']['config_file']
        35:    cookbook        'sshd'
        36:    source          'sshd_config.erb'
        37:    action          :create
        38:  end
        39: 
```

This PR fix them. ;)

### CODE REVIEW

**Comment by chr4** [comment]
Hi there! Thanks for your contribution!
I've tried to migrate the integration tests to Github Actions, as you've already noticed :) 

It's not yet finished, especially tests seem to run in a duplicate manner. Feel free to also contribute here! 

The overall state of your pull requests looks good to me; I wanted to fix the test and get them running before merging though, so we can be sure it works still on all distributions.

I'm a little busy currently, so please bear with me :( and feel welcome to push the Github Actions forward as well (as you're already trying), if you have the time!

**Comment by rnt** [comment]
> Hi there! Thanks for your contribution!
> I've tried to migrate the integration tests to Github Actions, as you've already noticed :)
> 
> It's not yet finished, especially tests seem to run in a duplicate manner. Feel free to also contribute here!
> 
> The overall state of your pull requests looks good to me; I wanted to fix the test and get them running before merging though, so we can be sure it works still on all distributions.
> 
> I'm a little busy currently, so please bear with me :( and feel welcome to push the Github Actions forward as well (as you're already trying), if you have the time!

I also noticed what you are doing, so I integrated #24 into mine.
This github workflows is new for me, so I will have to read a little more to help.

If you succeed before me, I integrate it.
If I get it first, it goes in the same MR.

I'm in the same situation as you, very short of time.
As soon as I can, I'll be reviewing it.

:+1:

**Comment by rnt** [comment]
@chr4 ,
Ready to merge!

**Comment by chr4** [comment]
Wow, that was quick! Nice, well done. Looks good to me. 

Would you mind being added to the README's "Contributors" list? 

I'll merge and release `v3.0.0` to supermarket then. 

Thanks again!

**Comment by chr4** [comment]
Closing this in favor of https://github.com/chr4-cookbooks/sshd/pull/25 (rebased version, with README fame).

**Comment by chr4** [comment]
Tried cleaning up, will merge if you give your ok (used `fixup` a few times).

**Pull request closed without merging**
