### PR TITLE
Add Arch and Amazon Linux SFTP subsystem support.

### PR DESCRIPTION
**Pull request by JHBoricua**
Added support for enabling the SFTP subsystem on Amazon Linux and (per #9) Arch Linux. 

Signed-off-by: Jose Hernandez <jhboricua@gmail.com>

### CODE REVIEW

**Comment by chr4** [comment]
Thank you, this looks really cool! 

I think to fix actions, it's required to migrate to the `main` branch in https://github.com/chr4-cookbooks/sshd/blob/master/.github/workflows/chef.yml#L21.

**Comment by chr4** [comment]
Nice, all green :) 

Will merge, thanks for your contribution! Feel free to add yourself to the Contributors list in README if you like!

**Comment by JHBoricua** [comment]
Glad it worked. Thanks.

**Comment by chr4** [comment]
Released `3.1.0` on [supermarket](https://supermarket.chef.io/cookbooks/sshd/versions/3.1.0).

**Pull request merged**
